epochs: 150
batch_size: 64
dropout: 0
lr: 0.0005
lr_adv: 0.0005
hidden_size_pi: 10
hidden_size_phi: 10
hidden_size_adv: 10
weight_decay: 0
gamma: 100
action_fair: "af_wstein"
value_fair: "vmm"
m: "dm"
loss: "confusion"
name: "Value Unfair Action fair"